# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='script',
            field=models.TextField(blank=True),
        ),
    ]
